/**
 * Turn the viewer's single-file build into a TS module the CLI can import and
 * `bun build --compile` can bake into the standalone binary.
 *
 * We base64-encode the HTML so there's nothing to escape and no loader
 * ambiguity (Bun treats .html specially; a plain .ts string import is
 * unambiguous and works identically in `bun run` and a compiled binary).
 *
 * Run after `npm run build:embed -w viewer`.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const htmlPath = path.resolve(here, "../../viewer/dist-embed/index.html");
const outPath = path.resolve(here, "../embed.ts");

if (!fs.existsSync(htmlPath)) {
  console.error(
    `viewer build not found at ${htmlPath}\n` +
      `run: npm run build:embed -w viewer`,
  );
  process.exit(1);
}

const html = fs.readFileSync(htmlPath, "utf-8");
const b64 = Buffer.from(html, "utf-8").toString("base64");
const banner =
  "// GENERATED by cli/scripts/gen-embed.ts - do not edit. " +
  "Holds the viewer's single-file build.\n";
fs.writeFileSync(
  outPath,
  `${banner}export const VIEWER_HTML_B64 = ${JSON.stringify(b64)};\n`,
);
console.log(
  `wrote ${path.relative(process.cwd(), outPath)} (${(html.length / 1024).toFixed(0)} KB of HTML)`,
);
